### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by ib00** [edubart/sokol_gp#2]
Cool project! 

What are further plans with this project?

In particular, I am wondering if there are any plans extend the API 
(and maybe support nanovg https://github.com/memononen/nanovg).

**Comment by edubart** [comment]
I've no plans to support drawing vector graphics at this moment, this is way complex than it sounds. Regarding future plans I consider the project finished and it already fulfills its job.

Would be cool to have a vector graphics API on top Sokol like NanoVG, I could work on that someday, who knows, but not of free will because at this moment and I don't need such feature.
