### ISSUE TITLE
Batching draw calls with different colors

### ISSUE THREAD

**Issue by kkukshtel** [edubart/sokol_gp#30]
I'd like to start a discussion about ways to batch calls that use a different color. I'm trying to use the default sokol_gp pipeline to draw entites that have slight variances in color (like a particle system), and the color differences between any two objects means that the draw calls aren't batched for GP.

I can think of a few ways to potentially implement this, but I wanted to open a discussion here with @edubart about what you think would work as well.

Off the top of my head, I think doing something like supplying a texture that gets written to for colors for submitted calls could work. You could set a max size for this texture similar to setting the max vert count, and that texture is created and written to for colors. So to start maybe just something like a 64x64 texture would support 64^2 unique colors before needing to do a new call.

I think having this as an option as well would be nice — the overhead of updating a texture per-frame may not be worth it for some use cases, but I think the benefits would definitely be felt by me. Interested to hear what you think!

**Comment by edubart** [comment]
I don't think the solution you suggested of using textures is a good idea, seems hacky and limited.

The way I would implement per vertex coloring is as the name suggests, to add a color attribute to the `_sgp_vertex`, so:

```c
typedef struct _sgp_vertex {
    sgp_vec2 position; // 2 floats
    sgp_vec2 texcoord; // 2 floats
    sgp_color color; // 4 floats
} _sgp_vertex;
```

Then rewrite all shaders to make use of per vertex color instead of a color uniform, this would be a good amount of  refactoring in the library.

As you can notice this would double the number of floats dispatched from the CPU to GPU when drawing, for all draw calls, meaning the bus bandwidth between CPU and GPU would double per frame, this can impact performance for everyone, we would have to benchmark how much. However one benefit it's that more draw calls would be merged between `sgp_set_color` changes, so it could pay off.

If the performance impact is too big for other users not needing this feature, we could maybe enable it via an ifdef, or double the shaders, pipeline and APIs, but I want to avoid that route, because it adds unwanted complexity to the library.

The feature you need was actually planned, but never had time or own need do it yet, as you can see in the README:

>#### Future features planned
>These are features I would like to implement someday in the future (if there is enough interest).
>
>- Draw textured triangles
>- Support drawing primitives with colored vertices

**Comment by edubart** [comment]
Worth mentioning, that I tried per vertex coloring in the past, it's in the branch https://github.com/edubart/sokol_gp/tree/colored_pips

But at the time my goal was just raw performance, not this feature, I was comparing using color per vertex VS color per draw call, and color per draw call won at the time in terms of performance. But makes sense to take branch forward to have the feature you need.

**Comment by edubart** [comment]
This was implemented recently in the master branch. Actually the performance improved for me in my `sample-bench.c` benchmark :grimacing:, I got about +20% improvement in FPS.
