### ISSUE TITLE
Batching of LineStrips

### ISSUE THREAD

**Issue by questor** [edubart/sokol_gp#33]
Hi!
I'm using your project and had a small issue with automatic batching. When drawing LineStrips it's automatically batching the strips which results in wrong draw lines between the original commands. Think about draw strip 1 (with points 0,1,2,3) and strip 2 (with points 4,5,6,7) and batching will concat the calls will result in a wrongly drawn line between point 3 and point 4).

For my usecase it's fine to disable automatically batching, but I think the call that checks if batching is possible should forbid a merge between line-strips (triangle-strips might also be impacted).

Thanks for your library, it's helping my toy-projects a lot!

**Comment by edubart** [comment]
Oh this really looks like a bug, will take a look eventually.

**Comment by edubart** [comment]
Was looking today, this as a issue before but since release v0.4.0 merging of batch calls with LINE_STRIP or TRIANGLE_STRIP was forbidden, which fixed this issue. Worth mentioning that by the time you reported this issue this release was already out there, maybe you just need to update your `sokol_gp.h` to a newer release.

**Comment by questor** [comment]
thanks for your investigation!
