### ISSUE TITLE
Framebuffer example does not work with antialiasing (MSAA)

### ISSUE THREAD

**Issue by zufari4** [edubart/sokol_gp#37]
Hi. I wanted the texture to display antialiased shapes in the example "sample-framebuffer.c". 
![msaa](https://github.com/user-attachments/assets/9ec547c1-13b8-4ae4-92b1-204f637aec51)
But when I set `sapp_desc.sample_count ` > 1 I get an error.
![err](https://github.com/user-attachments/assets/d0d2114d-eca9-4c58-b779-ac58844992a7)
Please tell me how I can modify the example so that it works with antialiasing? 
I tried to set different formats here but it didn't help ` fb_depth_image_desc.pixel_format`

**Comment by edubart** [comment]
I have update the framebuffer and primitives examples to use multi sampling to shapes are antialiased. Turns out you need to create a "resolve" image for the framebuffer, so it's a bit more work, but this is documented in Sokol. Just take a look in the new framebuffer sample source code to know how to do it. This was node in commit https://github.com/edubart/sokol_gp/commit/7080d452adb1d282f1912a9e4467c6b924c172cb.
