### ISSUE TITLE
Function to pass in matrix directly instead of needing to rebuild it with individual calls to translate/rotate scale

### ISSUE THREAD

**Issue by kkukshtel** [edubart/sokol_gp#38]
As the title says, it would be nice if there was a way to pass in a matrix directly instead of needing to rebuild it from the matrix functions.

**Comment by edubart** [comment]
Fair, maybe I could add `sgp_set_matrix` and `sgp_get_matrix` for more low level matrix operation.

Then would make sense also to add `sgp_mat2x3_translate`, `sgp_mat2x3_rotate` and `sgp_mat2x3_eye` so you could actually operate on a matrix.

**Comment by edubart** [comment]
Actually you can get/set matrix already by querying the state, eg:

```c
sgp_state *state = sgp_query_state();
sgp_mat2x3 transform = state->transform; // Get transform matrix
state->transform = transform; // Set transform matrix
```

Since this is already doable with a few lines of code, no need to implement shortcuts, it would be redundant, and direct state manipulation is more powerful. Also I consider manual manipulation of the matrix a low level thing to do, outside the scope of a high level API, and not a typical thing people will often do.

**Comment by kkukshtel** [comment]
Oh this is great — I think it would work perfectly! I'll give it a go.
