### ISSUE TITLE
circles

### ISSUE THREAD

**Issue by konsumer** [edubart/sokol_gp#40]
Here is a way to draw circles:

```c
#include <math.h>
#include "sokol_gp.h"

static const int num_segments = 60;

void sgp_draw_outline_circle(float cx, float cy, float radius) {
  const float step = 2.0f * M_PI / num_segments;
  for (int i = 0; i < num_segments; i++) {
    float a1 = step * i;
    float a2 = step * (i + 1);
    sgp_draw_line(
      cx + cosf(a1) * radius,
      cy + sinf(a1) * radius,
      cx + cosf(a2) * radius,
      cy + sinf(a2) * radius
    );
  }
}

void sgp_draw_filled_circle(float cx, float cy, float radius) {
  const float step = radius / num_segments;
  for (float y = -radius; y <= radius; y += step) {
    float x = sqrtf(radius * radius - y * y);
    sgp_draw_filled_rect(
      cx - x,
      cy + y,
      x * 2,
      step
    );
  }
}
```

with similar projection to the rect-demo, this makes a decent target:

```c
sgp_set_color(0.1f, 0.1f, 0.1f, 1.0f);
sgp_clear();
int c = 0;
for (float i = 1.0f;i>0; i-= 0.1f) {
  if (c++ % 2 == 0) {
    sgp_set_color(1.0f, 1.0f, 1.0f, 1.0f);
  }else {
    sgp_set_color(1.0f, 0.0f, 0.0f, 1.0f);
  }
  sgp_draw_filled_circle(0, 0, i);
}
```

<img width="801" alt="Screenshot 2024-11-13 at 12 21 51 AM" src="https://github.com/user-attachments/assets/eda313a6-80d1-4f99-b4d0-966d09d84fd5">

It's not perfect, but higher `num_segments` can improve look, as a balance between speed/quality.

If there is interest I can PR for this.

**Comment by edubart** [comment]
Thanks for the suggestion, this may help others!

But my sentiments is that this should not be included officially in the `sokol_gp.h` header, the scope of this header is to draw only very basic shapes.

Maybe we could have a library like `sokol_gp_extra.h` with more complex shape drawing functions like circles, arcs, regular polygons, eclipses, bezier curves, both filled and outlined (one inspiration is https://iquilezles.org/articles/distfunctions2d/). You see the possibilities of possible shapes are endless and application specific, so I think supporting everything people may want is complicated.

Also there are open questions like whether these shapes should be drawn as a fragment shader (with SDFs) or as triangles. Drawing as SDFs has some advantages on efficiency for some cases and also possibility to make pixel perfect antialiased shapes.

I am closing because, this is out of the project scope for now.
