### ISSUE TITLE
Add a sokol_gp "backend" for sokol_fontash (instead of requiring sokol_gl)

### ISSUE THREAD

**Issue by kkukshtel** [edubart/sokol_gp#43]
Hello!

I finally got sokol_fontstash setup in my engine but am running into some issues around integrating it with sokol_gp, namely around sorting/ordering the text in relationship to things created with sokol_gp. sokol_fontash uses sokol GL and as such has a slightly different call path than normal sg objects, so interleaving draw calls from GP and GL is a bit tricky.

What I'd like would be if sokol_gp just provided it's own "backend" for sokol_fontash that basically routes the API to sokol_gp functions instead of sokol_gl. 

On the surface it doesn't seem to difficult, as many of the GL calls have very similar API surface to GP:
https://github.com/floooh/sokol/blob/8c989e39c008149a8a6b89cd001a2af3dbe3a8c2/util/sokol_fontstash.h#L2181

Additionally, instead of it being a core part of sokol_gp, it could similarily be in a utils folder?

I'd also be happy to sponsor this work if you're interested!

**Comment by edubart** [comment]
> around sorting/ordering the text in relationship to things created with sokol_gp

This makes sense, as a general rule you should not mix drawings of Sokol GP and other APIs (Sokol GL, GL, Sokol, etc) in the same screen region, because Sokol GP is free to rearrange the drawing order to optimize batching, which can lead to undesired draw ordering in respect to external drawing APIs. If you really want to mix, you will need to flush the draw calls before calling external drawing APIs.

> I'd also be happy to sponsor this work if you're interested!

Unfortunately I have little time to work on a Sokol GP backend to fontstash. But there is a simpler solution to your problem, you could just flush SGP draws calls by calling `sgp_flush()` before mixing other drawing APIs (eg Sokol GL).
Here a simple concept:

```c
static void frame(void) {
    // Begin a render pass.
    sg_pass pass = {.swapchain = sglue_swapchain()};
    sg_begin_pass(&pass);

    // Begin drawing with SGP
    int width = sapp_width(), height = sapp_height();
    float ratio = width/(float)height;
    sgp_begin(width, height);
    sgp_viewport(0, 0, width, height);
    sgp_project(-ratio, ratio, 1.0f, -1.0f);
    sgp_clear();

    // Draw rectangle A
    sgp_set_color(0.0f, 0.0f, 1.0f, 1.0f);
    sgp_draw_filled_rect(0.0f, 0.0f, 1.0f, 1.0f);
    sgp_flush(); // Dispatch all draw calls, to maintain strict ordering

    // Draw some text with fontstash (using Sokol GL under the hood)
    fonsDrawText(...);

    // Draw rectangle B
    sgp_set_color(0.0f, 0.0f, 1.0f, 1.0f);
    sgp_draw_filled_rect(-1.0f, -1.0f, 1.0f, 1.0f);

    // Finish drawing with SGP
    sgp_flush();
    sgp_end();

    // End render pass.
    sg_end_pass();
    sg_commit();
}
```

In this example rectangle A and B will not be batched together, because the `sgp_flush()` just before the `fonsDrawText()` call will flush the batcher.

This is a proof of concept, there are still other questions about if you need to save/restore Sokol GL state when mixing APIs, I have not tested this really, so it's something it could be needed, unsure.

**Comment by edubart** [comment]
I am marking this a closed, because I have provided a solution that need no changes in Sokol GP. If you attempt trying it, let us know if you got it to working.
